---
- name: Deploy
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  vars:
    custom_addons: "{{ lookup('file', 'repos/{{ git_repo }}.json') | from_json }}"
    odoo_config: "{{ lookup('file', 'odoo/{{ odoo_conf }}.json') | from_json }}"

  tasks:
    - name: Check if the directory exists
      ansible.builtin.stat:
        path: "{{ odoo_config.addons_directory }}{{ custom_addons.pool_directory }}{{custom_addons.origin.repo_name}}"
      register: dir_to_check

    - name: Set Addons Dir if exists
      set_fact:
        addon_dir: "{{ dir_to_check.stat.path }}"
      when: dir_to_check.stat.isdir is defined

    - name: Set Addons Dir if not exists
      set_fact:
        addon_dir: "{{ odoo_config.addons_directory }}{{ custom_addons.pool_directory }}{{custom_addons.origin.repo_name}}"
      when: dir_to_check.stat.isdir is not defined

    - name: Create Addon pool_directory
      shell: mkdir -p "{{ odoo_config.addons_directory }}{{ custom_addons.pool_directory }}"
      notify: 
          - Clone Repo
          - Update Odoo Config
      when: dir_to_check.stat.isdir is not defined

    - name: Performance a git Stash
      shell: git stash
      args:
        chdir: "{{ addon_dir }}"
      notify: Update Repo
      when: addon_dir is defined and dir_to_check.stat.isdir is defined

  handlers:
    - name: Clone Repo
      git:
        repo: "{{ custom_addons.origin.url }}"
        dest: "{{ addon_dir }}"
        clone: yes
        version: "{{ branch }}"
      when: addon_dir is defined

    - name: Update Odoo Config
      ansible.builtin.lineinfile:
        path: "{{ odoo_config.config }}"
        regexp: '^ADDLINE '
        insertbefore: '^#ADDLINE'
        line: '         ,{{addon_dir}}'
      notify: Restart Odoo
      when: addon_dir is defined

    - name: Update Repo
      git:
        repo: "{{ custom_addons.origin.url }}"
        dest: "{{ addon_dir }}"
        update: yes
        version: "{{ branch }}"
      notify: Restart Odoo
      when: addon_dir is defined and dir_to_check.stat.isdir is defined

    - name: Restart Odoo
      service: name=odoo state=restarted